spring:
  datasource:
    url: jdbc:h2:file:~/books
    username: sa
    password: geheim#123

  jpa:
    hibernate:
      # create, create-drop, validate, update, none
      ddl-auto: update

  h2:
    console:
      enabled: true





#server.port: 8888